version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: stop_service.sh
      timeout: 120
      runas: root
    - location: kill_service.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: init.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: start_service.sh
      timeout: 120
      runas: root
